{
 "title": "Iris predictor",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Setosa distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(prediction_distribution_bucket{pipeline=\"0.1.2\", label=\"0\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Versicolor distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(prediction_distribution_bucket{pipeline=\"0.1.2\", label=\"1\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Virginica distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(prediction_distribution_bucket{pipeline=\"0.1.2\", label=\"2\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(rpc_request_duration_seconds_bucket{method=\"pipeline/predict\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}